import './globals.css'
import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import { Providers } from './providers'

const inter = Kanit({ subsets: ['latin', 'thai'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className} suppressHydrationWarning>{children}</body>
      </Providers>
    </html>
  )
}
